name: Test with Rails head

on:
  schedule:
    - cron: ""

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0"]
        rails: ["head"]
        experimental: [true]

    continue-on-error: ${{ matrix.experimental }}
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test with Rake
      run: |
        COVERAGE=true bundle exec rake

    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: coverage-report-ruby-${{ matrix.ruby }}-rails-${{ matrix.rails }}
        path: coverage
